Traceback (most recent call last):
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/wakanamorlan/anaconda3/envs/py310/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from statsmodels.stats.weightstats import ttest_ind
t_stat, p_value, degree_of_freedom = ttest_ind(controll_results, treatment_results)
print(f"T-statistic: {t_stat:0.2f}")
print(f"p-value: {p_value:0.2f}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[18], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m[38;5;21;01m.[39;00m[38;5;21;01mweightstats[39;00m [38;5;28;01mimport[39;00m ttest_ind
[0;32m----> 2[0m t_stat, p_value, degree_of_freedom [38;5;241m=[39m ttest_ind([43mcontroll_results[49m, treatment_results)
[1;32m      3[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mT-statistic: [39m[38;5;132;01m{[39;00mt_stat[38;5;132;01m:[39;00m[38;5;124m0.2f[39m[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m      4[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mp-value: [39m[38;5;132;01m{[39;00mp_value[38;5;132;01m:[39;00m[38;5;124m0.2f[39m[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mNameError[0m: name 'controll_results' is not defined
NameError: name 'controll_results' is not defined

