Traceback (most recent call last):
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Wakana\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Wakana\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from statsmodels.stats.weightstats import ttest_ind
t_stat, p_value, degree_of_freedom = ttest_ind(controll_results, treatment_results)
print(f"T-statistic: {t_stat:0.2f}")
print(f"p-value: {p_value:0.2f}")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-18-33028541e236>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mfrom[0m [0mstatsmodels[0m[1;33m.[0m[0mstats[0m[1;33m.[0m[0mweightstats[0m [1;32mimport[0m [0mttest_ind[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mt_stat[0m[1;33m,[0m [0mp_value[0m[1;33m,[0m [0mdegree_of_freedom[0m [1;33m=[0m [0mttest_ind[0m[1;33m([0m[0mcontroll_results[0m[1;33m,[0m [0mtreatment_results[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mprint[0m[1;33m([0m[1;34mf"T-statistic: {t_stat:0.2f}"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mprint[0m[1;33m([0m[1;34mf"p-value: {p_value:0.2f}"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'controll_results' is not defined
NameError: name 'controll_results' is not defined

